# Generated by Django 5.0.3 on 2024-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_urlsource_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsource',
            name='identifier',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
