# Generated by Django 5.0.3 on 2024-03-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_urlsource_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsource',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='urlsource',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
    ]
