# Generated by Django 5.0.3 on 2024-03-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_add_description_field_to_urlsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsource',
            name='type',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
