# Generated by Django 5.0.3 on 2024-03-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_moved_type_field_to_title_in_urlsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsource',
            name='identifier',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='urlsource',
            name='url',
            field=models.CharField(help_text='The metadata source url', max_length=1000, unique=True),
        ),
    ]
