# Generated by Django 5.0.3 on 2024-03-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_added_unique_to_identifier_and_url_in_urlsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsource',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='urlsource',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='urlsource',
            name='description',
            field=models.CharField(blank=True, help_text='Metadata description', max_length=2500),
        ),
        migrations.AlterField(
            model_name='urlsource',
            name='identifier',
            field=models.CharField(help_text='Unique identifier found in metadata', max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='urlsource',
            name='title',
            field=models.CharField(blank=True, help_text='Metadata title', max_length=250),
        ),
    ]
