"""Create a baseline migrations

Revision ID: 09aaae524f88
Revises: a02b5c5e4550
Create Date: 2024-04-03 22:57:40.698510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09aaae524f88"
down_revision: Union[str, None] = "a02b5c5e4550"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("url", sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "url")
    # ### end Alembic commands ###
