"""Added updated_at and created_at on Document model

Revision ID: d23da94335b5
Revises: 332cc4b0cfb7
Create Date: 2024-04-03 23:01:38.922404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d23da94335b5"
down_revision: Union[str, None] = "332cc4b0cfb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("created_at", sa.DateTime(), nullable=True))
    op.add_column("documents", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "updated_at")
    op.drop_column("documents", "created_at")
    # ### end Alembic commands ###
