# # The Docker image that will be used to build your app
# image: javanile/mkdocs

# # Functions that should be executed before the build script is run
# before_script: []

# pages:
#   script:
#     - mkdocs build
#   artifacts:
#     paths:
#       - public
#   rules:
#     # This ensures that only pushes to the default branch will trigger
#     # a pages deploy
#     - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH


stages:
  - deploy # mandatory name for the stage to GitLab detect it's a Pages deployment

# Pages
pages: # mandatory name for the job to GitLab detect it's a Pages deployment
  stage: deploy
  image: javanile/mkdocs # Image containing tools required for mkdocs
  script: mkdocs build -d public
  artifacts:
    paths:
      - public # set public to be deploy
  needs: []
  only:
    - main # only update pages from main branch
