site_name: DADA-Forest
nav:
  - Home: index.md
  - Metadata Standards: metadata-standards.md
  - Metadata Examples: metadata-examples.md
  - Needs Analysis: needs-analysis.md
  - About: about.md
theme: readthedocs
markdown_extensions:
  - attr_list
  - tables
