name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: cd docs && pip install mkdocs
      - run: mkdocs gh-deploy --force --clean --verbose